### ISSUE TITLE
Should I learn something about basic datamining algorithms? like cluster, association rules

### ISSUE THREAD

**Issue by w237354468** [data-burst/data-engineering-roadmap#20]
As a data engineer, I usually process data tasks which are arranged by algorithm' team and I dont need to think about why they need that. But I think if I want to dive deeper with data, I need to know them better. 
So my question is should I learn something basic dataming algorithms(A porior, decision tree etc.) as a roadmap node?  And Why? 
Thank you!

**Comment by niyushabaghayi** [comment]
Hi @w237354468,
Thanks for your question! As data engineers, our primary focus is on designing, building, and maintaining data pipelines and infrastructure, which generally doesn't require deep knowledge of ML algorithms.
While understanding these algorithms can be helpful in certain cases—especially if you're working closely with machine learning or data science teams—it's not a core requirement for data engineering as defined in the `Fundamentals of Data Engineering` book.
Therefore, I wouldn't recommend adding these to the roadmap for data engineers. If your role involves more overlap with ML engineering, that's a different discussion, but for pure data engineering, these aren't essential.

Hope this helps!

**Comment by mostafaghadimi** [comment]
Hi @w237354468!


Thanks to the detailed response from @niyushabaghayi, I’d like to add a few more points. Data mining is a closely related field to both data analysis and machine learning. In smaller companies, a single individual may often be responsible for tasks across all three domains—handling machine learning models, performing data analysis, and managing data engineering workflows.

If you are passionate about data mining field, I highly recommend checking out [CS246: Mining of Massive Datasets](https://web.stanford.edu/class/cs246/), a popular course offered by Stanford University. It provides an in-depth exploration of data mining concepts and techniques, which can be highly relevant to real-world scenarios.

These fields are closely related, and their concepts are sometimes used interchangeably, which can lead to misunderstandings. The purpose of this data engineering roadmap is to clearly define the responsibilities of a data engineer, highlight key concepts, and introduce tools essential for entering the field. It also aims to provide structured guidance for professionals at different stages of their career—from junior to senior data engineers.

If you have any other questions, feel free to ask.


Thanks,
Mostafa

**Comment by w237354468** [comment]
Thank you guys so much for warm help!  I got it.

**Comment by w237354468** [comment]
Thank you guys so much for warm help! I got it.
